CREATE DATABASE Ecommerce;

USE Ecommerce;


CREATE TABLE Produto (
Id INT PRIMARY KEY AUTO_INCREMENT,
Nome VARCHAR(100) NOT NULL,
Descricao TEXT,
PrecoUnitario FLOAT NOT NULL,
Estoque INT NOT NULL
);

CREATE TABLE Venda (
Id INT PRIMARY KEY AUTO_INCREMENT,
DataVenda DATETIME NOT NULL,
Total FLOAT NOT NULL,
FormaPagamento VARCHAR(50) NOT NULL,
Desconto FLOAT DEFAULT 0,
StatusVenda VARCHAR(50) NOT NULL
);

CREATE TABLE VendaProduto (
VendaId INT NOT NULL,
ProdutoId INT NOT NULL,
PrecoUnitario FLOAT NOT NULL,
Quantidade INT NOT NULL,
Subtotal FLOAT AS (Quantidade * PrecoUnitario) STORED,
FOREIGN KEY (VendaId) REFERENCES Venda(Id) ON DELETE CASCADE,
FOREIGN KEY (ProdutoId) REFERENCES Produto(Id) ON DELETE CASCADE
);

CREATE TABLE Usuario (
Id INT PRIMARY KEY AUTO_INCREMENT,
Login VARCHAR(50) NOT NULL UNIQUE,
Senha VARCHAR(255) NOT NULL,
Ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE Login (
Usuario VARCHAR(50) NOT NULL,
Senha VARCHAR(255) NOT NULL,
FOREIGN KEY (Usuario) REFERENCES Usuario(Login)
);

INSERT INTO Usuario (Login, Senha) VALUES ('ADMIN','ADMIN');